# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 23:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_title', models.CharField(max_length=250)),
                ('article_content', models.TextField()),
                ('article_author', models.CharField(max_length=50)),
                ('article_date', models.DateTimeField()),
                ('article_rate', models.IntegerField()),
            ],
            options={
                'db_table': 'article',
            },
        ),
    ]
