# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 23:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='comment_author',
            field=models.EmailField(default='example@abc.com', max_length=254),
        ),
        migrations.AddField(
            model_name='comments',
            name='comment_content',
            field=models.TextField(default='Some text'),
        ),
        migrations.AddField(
            model_name='comments',
            name='comment_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 10, 26, 23, 56, 56, 417345)),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_rate',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterModelTable(
            name='comments',
            table='article_comments',
        ),
    ]
